/**
 * Client-side PDF generation for procurement tokens (and notices).
 *
 * Uses `pdf-lib` — a pure-JavaScript PDF writer with no native modules, so the
 * same code path works on web, Android and iOS. On web the generated bytes are
 * turned into a real file download (`FPP-1042-token.pdf`); on native, the caller
 * shows a message that downloading is available in the web version.
 *
 * All typography is drawn with built-in Helvetica, which supports only the
 * WinAnsi (CP1252) encoding — document text is therefore English. Every drawn
 * string passes through `safe()`, which strips characters Helvetica cannot
 * encode (Devanagari, Malayalam, emoji, ▸-style glyphs, …) so a localized
 * app profile can never crash the download with "WinAnsi cannot encode".
 */
import type { PDFFont, PDFPage } from 'pdf-lib';
import { Platform } from 'react-native';

import { formatDateLong, slotRange, type Booking } from '../data/mockData';

// pdf-lib is loaded lazily via dynamic import so its ~400 KB of minified code
// stays out of the initial JS bundle — the browser only fetches it the first
// time a user actually downloads a token or notice PDF. Only *types* are
// imported statically; they are erased at build time.
type PdfLib = typeof import('pdf-lib');
type PdfColor = ReturnType<PdfLib['rgb']>;

let pdfLibModule: Promise<PdfLib> | null = null;
function loadPdfLib(): Promise<PdfLib> {
  if (!pdfLibModule) pdfLibModule = import('pdf-lib');
  return pdfLibModule;
}

type Palette = {
  NAVY: PdfColor;
  NAVY_DARK: PdfColor;
  SAFFRON: PdfColor;
  GREY: PdfColor;
  GREY_LIGHT: PdfColor;
  WHITE: PdfColor;
  BLACK: PdfColor;
  GREEN: PdfColor;
};

let palette: Palette | null = null;

/** Build the colour palette from pdf-lib's own rgb() once loaded. */
function getColors(lib: PdfLib): Palette {
  if (!palette) {
    const { rgb } = lib;
    palette = {
      NAVY: rgb(0.051, 0.278, 0.631), // #0d47a1 — Colors.primary
      NAVY_DARK: rgb(0.039, 0.184, 0.42), // #0a2f6b — Colors.primaryDark
      SAFFRON: rgb(0.902, 0.318, 0), // #e65100 — Colors.saffron
      GREY: rgb(0.42, 0.46, 0.49), // Colors.textSecondary
      GREY_LIGHT: rgb(0.78, 0.79, 0.81),
      WHITE: rgb(1, 1, 1),
      BLACK: rgb(0.1, 0.1, 0.1),
      GREEN: rgb(0.086, 0.51, 0.23),
    };
  }
  return palette;
}

// --------------------------------------------------------------------- types

export type TokenPdfInput = {
  booking: Booking;
  farmer?: {
    id?: string;
    name?: string;
    mobile?: string;
    aadhaar?: string;
    village?: string;
    district?: string;
  } | null;
  centre?: { address?: string } | null;
};

export type NoticePdfInput = {
  title: string;
  dept: string;
  date: string;
};

export type PdfOutcome = { ok: true } | { ok: false; reason: 'unsupported' | 'error' };

// --------------------------------------------------------------------- util

const A4_W = 595.28;
const A4_H = 841.89;

/** Center text horizontally on the page (pdf-lib has no text-align). */
function centerX(page: PDFPage, text: string, size: number, font: PDFFont): number {
  return (page.getWidth() - font.widthOfTextAtSize(text, size)) / 2;
}

/** Truncate a value so it fits within maxWidth instead of overflowing. */
function fit(text: string, font: PDFFont, size: number, maxWidth: number): string {
  if (font.widthOfTextAtSize(text, size) <= maxWidth) return text;
  let out = text;
  while (out.length > 3 && font.widthOfTextAtSize(`${out}…`, size) > maxWidth) {
    out = out.slice(0, -1);
  }
  return `${out}…`;
}

function maskAadhaar(aadhaar?: string): string {
  if (!aadhaar) return '—';
  const digits = aadhaar.replace(/[^\d]/g, '');
  return digits.length >= 4 ? `XXXX XXXX ${digits.slice(-4)}` : '—';
}

// WinAnsi (CP1252) is the only encoding the built-in PDF fonts support. Any
// character outside it — Devanagari "क", Malayalam, emoji, "►" — throws
// "WinAnsi cannot encode …" at draw time. This whitelist covers ASCII,
// Latin-1 punctuation/letters and the CP1252 extras (– — … ' ' " " • » €).
const WINANSI_CHAR =
  /^[\u0020-\u007E\u00A0-\u00FF\u20AC\u201A\u0192\u201E\u2026\u2020\u2021\u02C6\u2030\u0160\u2039\u0152\u017D\u2018\u2019\u201C\u201D\u2022\u2013\u2014\u02DC\u2122\u0161\u203A\u0153\u017E\u0178]$/;

/** Drop characters the built-in fonts cannot encode; fall back when empty. */
function safe(text: string, fallback = '—'): string {
  const out = Array.from(text ?? '')
    .filter((ch) => WINANSI_CHAR.test(ch))
    .join('')
    .trim();
  return out.length > 0 ? out : fallback;
}

function timestampLabel(): string {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, '0');
  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  return `${d.getDate()} ${months[d.getMonth()]} ${d.getFullYear()}, ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

/** Draw a document footer with generated-at + demo disclaimer. */
function drawFooter(
  page: PDFPage,
  fonts: { regular: PDFFont; bold: PDFFont },
  colors: Palette,
  generatedOn: string,
  disclaimer: string
) {
  const { regular, bold } = fonts;
  const { GREY, GREY_LIGHT, GREEN } = colors;
  const w = page.getWidth();
  page.drawLine({
    start: { x: 44, y: 74 },
    end: { x: w - 44, y: 74 },
    thickness: 0.6,
    color: GREY_LIGHT,
  });
  page.drawText(generatedOn, { x: 44, y: 58, size: 9, font: regular, color: GREY });
  page.drawText(disclaimer, { x: w - 44, y: 58, size: 8, font: bold, color: GREEN });
}

/** Save PDF bytes as a browser file download (web only). */
function saveToDisk(bytes: Uint8Array, filename: string) {
  const blob = new Blob([bytes as BlobPart], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1500);
}
// -------------------------------------------------------------- token build

async function buildTokenPdf(input: TokenPdfInput): Promise<Uint8Array> {
  const { booking, farmer, centre } = input;
  const lib = await loadPdfLib();
  const { PDFDocument, StandardFonts } = lib;
  const colors = getColors(lib);
  const { NAVY, NAVY_DARK, SAFFRON, GREY, GREY_LIGHT, WHITE, BLACK, GREEN } = colors;
  const doc = await PDFDocument.create();
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const page = doc.addPage([A4_W, A4_H]);

  // Double navy border — the admit-card look.
  page.drawRectangle({
    x: 12, y: 12, width: A4_W - 24, height: A4_H - 24,
    borderColor: NAVY_DARK, borderWidth: 2.5,
  });
  page.drawRectangle({
    x: 17, y: 17, width: A4_W - 34, height: A4_H - 34,
    borderColor: NAVY, borderWidth: 0.75,
  });

  // Header band.
  const bandY = A4_H - 72;
  page.drawRectangle({ x: 19, y: bandY, width: A4_W - 38, height: 40, color: NAVY_DARK });
  page.drawText('NATIONAL FARMER PROCUREMENT PORTAL', {
    x: centerX(page, 'NATIONAL FARMER PROCUREMENT PORTAL', 14, bold),
    y: A4_H - 56, size: 14, font: bold, color: WHITE,
  });
  page.drawText('Department of Consumer Affairs · Government of India', {
    x: centerX(page, 'Department of Consumer Affairs · Government of India', 9, regular),
    y: A4_H - 66, size: 9, font: regular, color: WHITE,
  });
  page.drawRectangle({ x: 19, y: bandY - 10, width: A4_W - 38, height: 4, color: SAFFRON });

  // Title (English only — Helvetica/WinAnsi cannot encode Indic scripts).
  const TITLE = 'PROCUREMENT TOKEN';
  page.drawText(TITLE, {
    x: centerX(page, TITLE, 15, bold),
    y: A4_H - 128, size: 15, font: bold, color: NAVY_DARK,
  });

  // Big token number.
  const token = booking.token;
  page.drawText(token, {
    x: centerX(page, token, 44, bold),
    y: A4_H - 188, size: 44, font: bold, color: NAVY,
  });
  page.drawRectangle({
    x: (A4_W - 180) / 2, y: A4_H - 216, width: 180, height: 3, color: SAFFRON,
  });

  // Detail rows ("label — value" two-column layout).
  const rows: { label: string; value: string }[] = [
    { label: 'FARMER NAME', value: farmer?.name ?? booking.farmerName },
    { label: 'FARMER ID', value: farmer?.id ?? '—' },
    { label: 'MOBILE', value: farmer?.mobile ?? '—' },
    { label: 'AADHAAR', value: maskAadhaar(farmer?.aadhaar) },
    { label: 'PROCUREMENT CENTRE', value: booking.centreName },
    {
      label: 'CENTRE ADDRESS',
      value: centre?.address && centre.address.length > 0 ? centre.address : booking.centreName,
    },
    { label: 'DATE', value: formatDateLong(booking.date) },
    { label: 'TOKEN TIME', value: slotRange(booking.slotStart, booking.slotEnd) },
    { label: 'PRODUCE', value: booking.produce },
    { label: 'QUANTITY', value: `${booking.quantityKg} kg` },
    { label: 'STATUS', value: booking.status },
  ];

  let y = A4_H - 258;
  const labelX = 48;
  const valueX = 210;
  const rowH = 27;
  const valueMaxW = A4_W - valueX - 48;

  rows.forEach((row, i) => {
    if (i > 0) {
      page.drawLine({
        start: { x: labelX, y: y + 8 },
        end: { x: A4_W - 48, y: y + 8 },
        thickness: 0.4,
        color: GREY_LIGHT,
      });
    }
    page.drawText(row.label, { x: labelX, y, size: 10, font: bold, color: GREY });
    page.drawText(fit(safe(row.value), regular, 12, valueMaxW), {
      x: valueX, y, size: 12, font: regular, color: BLACK,
    });
    y -= rowH;
  });

  // Instructions footnote ("»" is WinAnsi-safe; "►" is not).
  page.drawText('» Arrive at the centre before your token time.', {
    x: labelX, y: y + 2, size: 10, font: bold, color: GREEN,
  });
  page.drawText('» Carry this token (printout or on your phone) and a valid ID.', {
    x: labelX, y: y - 16, size: 10, font: bold, color: GREEN,
  });

  drawFooter(
    page,
    { regular, bold },
    colors,
    `Generated on ${timestampLabel()}`,
    'Prototype document · not an official receipt'
  );

  return doc.save();
}

// -------------------------------------------------------------- notice build

async function buildNoticePdf(input: NoticePdfInput): Promise<Uint8Array> {
  const lib = await loadPdfLib();
  const { PDFDocument, StandardFonts } = lib;
  const colors = getColors(lib);
  const { NAVY_DARK, SAFFRON, GREY, WHITE, BLACK } = colors;
  const doc = await PDFDocument.create();
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const page = doc.addPage([A4_W, A4_H]);

  page.drawRectangle({
    x: 12, y: 12, width: A4_W - 24, height: A4_H - 24,
    borderColor: NAVY_DARK, borderWidth: 2.5,
  });

  // Header band.
  page.drawRectangle({ x: 19, y: A4_H - 70, width: A4_W - 38, height: 40, color: NAVY_DARK });
  page.drawText('NOTICE', {
    x: centerX(page, 'NOTICE', 15, bold),
    y: A4_H - 54, size: 15, font: bold, color: WHITE,
  });
  page.drawRectangle({ x: 19, y: A4_H - 84, width: A4_W - 38, height: 4, color: SAFFRON });

  const title = fit(safe(input.title, 'Notice'), bold, 16, A4_W - 96);
  page.drawText(title, { x: 44, y: A4_H - 130, size: 16, font: bold, color: NAVY_DARK });

  page.drawText(safe(input.dept), { x: 44, y: A4_H - 152, size: 11, font: regular, color: GREY });
  page.drawText(safe(input.date), { x: 44, y: A4_H - 168, size: 11, font: regular, color: GREY });

  const bodyLines = [
    'This notice was downloaded from the National Farmer Procurement Portal.', '',
    'It is a prototype document generated in the browser. It does not carry any',
    'legal standing and is not an official communication of the Government of India.',
  ];

  let y = A4_H - 220;
  for (const line of bodyLines) {
    page.drawText(line, { x: 44, y, size: 12, font: regular, color: BLACK });
    y -= line.length === 0 ? 12 : 20;
  }

  drawFooter(
    page,
    { regular, bold },
    colors,
    `Generated on ${timestampLabel()}`,
    'Prototype document · not an official notice'
  );

  return doc.save();
}

// ----------------------------------------------------------------- public

/** True when this platform can produce a real file download. */
export function canDownloadPdf(): boolean {
  return Platform.OS === 'web';
}

/** Build & download the procurement token as a PDF. Returns an outcome. */
export async function downloadTokenPdf(input: TokenPdfInput): Promise<PdfOutcome> {
  if (Platform.OS !== 'web') return { ok: false, reason: 'unsupported' };
  try {
    const bytes = await buildTokenPdf(input);
    const safe = input.booking.token.replace(/[^A-Z0-9-]/gi, '') || 'token';
    saveToDisk(bytes, `${safe}-token.pdf`);
    return { ok: true };
  } catch (error) {
    console.warn('Token PDF generation failed', error);
    return { ok: false, reason: 'error' };
  }
}

/** Build & download a public notice as a PDF. Returns an outcome. */
export async function downloadNoticePdf(input: NoticePdfInput): Promise<PdfOutcome> {
  if (Platform.OS !== 'web') return { ok: false, reason: 'unsupported' };
  try {
    const bytes = await buildNoticePdf(input);
    const slug = input.title.toLowerCase().replace(/[^a-z0-9]+/gi, '-').slice(0, 40).replace(/-+$/, '');
    saveToDisk(bytes, `notice-${slug || 'document'}.pdf`);
    return { ok: true };
  } catch (error) {
    console.warn('Notice PDF generation failed', error);
    return { ok: false, reason: 'error' };
  }
}